import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
// import {BsSearch} from 'react-icons/bs'
// import dotenv from 'dotenv'
// dotenv.config()


export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)

  const url = `api.openweathermap.org/data/2.5/weather?q=London&units=imperial&APPID=8d8369585ca53ff9172607afec4f77a4`
 
  const fetchWeather = (e) =>{
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src='https://images.unsplash.com/photo-1565118531796-763e5082d113?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80' 
      // layout='fill'
      classname='object-cover'
      />
    </div>
  )
}
